import Button from './Button.jsx'
import Feature from './Feature.jsx'
import Heading from './Heading.jsx'
import Img from './Img.jsx'
import Input from './Input.jsx'
import RatingBar from './RatingBar.jsx'
import Section from './Section.jsx'
import Template from './Template.jsx'
import Text from './Text.jsx'
import Header from './Header.jsx'
import Footer from './Footer.jsx'
import Checkbox from './Checkbox.jsx'
import Pagination from './Pagination.jsx'
import ReactTable from './ReactTable.jsx'

export {Button,Feature,Heading,Img,Input,RatingBar,Section,Template,Text,Header,Footer,Checkbox,Pagination,ReactTable} 
